// Code generated by scripts/generate-platform-tokens.mjs; DO NOT EDIT.
// Source: tokens/bytedesk.tokens.json
// Source SHA-256: d2e30ea21f14a61c8f88116691e89ba853ecc8acb790b99a4d3e6906424451a8

package bytedesktokens

const (
	TokenSourceSHA256                    = "d2e30ea21f14a61c8f88116691e89ba853ecc8acb790b99a4d3e6906424451a8"
	TokenBreakpointCompactMax            = "719px"
	TokenBreakpointStandardMin           = "720px"
	TokenBreakpointUltrawideMin          = "1600px"
	TokenBreakpointWideMin               = "1200px"
	TokenColorAccentDefault              = "#0079F2"
	TokenColorAccentEmphasis             = "#468CE8"
	TokenColorAccentFg                   = "#E8F1FB"
	TokenColorAccentMuted                = "#255DA5"
	TokenColorAccentSubtle               = "#193356"
	TokenColorBgBase                     = "#101316"
	TokenColorBgElevated                 = "#24282D"
	TokenColorBgOverlay                  = "#2B3036"
	TokenColorBgSubtle                   = "#171A1D"
	TokenColorBgSurface                  = "#1D2125"
	TokenColorBlue100                    = "#0E2037"
	TokenColorBlue200                    = "#193356"
	TokenColorBlue300                    = "#1F487C"
	TokenColorBlue400                    = "#255DA5"
	TokenColorBlue50                     = "#071221"
	TokenColorBlue500                    = "#0079F2"
	TokenColorBlue600                    = "#468CE8"
	TokenColorBlue700                    = "#71A7EF"
	TokenColorBlue800                    = "#9CC0F1"
	TokenColorBlue900                    = "#C7D9F2"
	TokenColorBorderDefault              = "#3A3E42"
	TokenColorBorderDimmer               = "#303438"
	TokenColorBorderDimmest              = "#272A2C"
	TokenColorBorderStronger             = "#44484C"
	TokenColorBorderStrongest            = "#4C4F52"
	TokenColorBrandOrange                = "#EC4E02"
	TokenColorBrandOrangeMuted           = "#D96D00"
	TokenColorChartAxis                  = "#A2A8B2"
	TokenColorChartGrid                  = "#31343F"
	TokenColorChartPlot                  = "#1A1C25"
	TokenColorChartSelection             = "#468CE8"
	TokenColorChartSeries1               = "#0079F2"
	TokenColorChartSeries2               = "#1DB8CE"
	TokenColorChartSeries3               = "#A170EB"
	TokenColorChartSeries4               = "#EA5DA9"
	TokenColorChartSeries5               = "#EC4E02"
	TokenColorChartSeries6               = "#009118"
	TokenColorChartSeries7               = "#DFA700"
	TokenColorChartSeries8               = "#E52222"
	TokenColorDeskAgentic                = "#1B3060"
	TokenColorDeskDeveloper              = "#2F2D55"
	TokenColorDeskFiles                  = "#013752"
	TokenColorDeskProjects               = "#282F56"
	TokenColorDeskSessions               = "#193356"
	TokenColorDeskSystem                 = "#1D354B"
	TokenColorInteractiveBlue            = "#0079F2"
	TokenColorInteractiveFocus           = "#71A7EF"
	TokenColorSemanticDanger             = "#E52222"
	TokenColorSemanticDangerBg           = "#2A1212"
	TokenColorSemanticDangerLine         = "#7A2424"
	TokenColorSemanticInfo               = "#1DB8CE"
	TokenColorSemanticInfoBg             = "#0C2226"
	TokenColorSemanticInfoLine           = "#1A5A64"
	TokenColorSemanticSuccess            = "#009118"
	TokenColorSemanticSuccessBg          = "#0C2414"
	TokenColorSemanticSuccessLine        = "#165C22"
	TokenColorSemanticSuccessMuted       = "#007012"
	TokenColorSemanticWarning            = "#DFA700"
	TokenColorSemanticWarningBg          = "#241E0C"
	TokenColorSemanticWarningLine        = "#6B5A14"
	TokenColorTextDisabled               = "#626A74"
	TokenColorTextOnBrand                = "#FFE2D8"
	TokenColorTextPrimary                = "#E6E8EB"
	TokenColorTextSecondary              = "#A1A8B1"
	TokenColorTextTertiary               = "#7E8792"
	TokenDepthAttentionGlow              = "0 0 20px #EC4E0238"
	TokenDepthFocusGlow                  = "0 0 0 1px #1B84F3, 0 0 24px #1B84F34D"
	TokenDepthRaisedDark                 = "inset 0 1px 0 #FFFFFF08, 0 8px 20px #05080D66"
	TokenDepthRaisedLight                = "inset 0 1px 0 #FFFFFFE6, 0 8px 20px #17203317"
	TokenDepthShellDark                  = "inset 0 1px 0 #FFFFFF0A, 0 24px 56px #05080DB8, 0 8px 20px #07182E66"
	TokenDepthShellLight                 = "inset 0 1px 0 #FFFFFFCC, 0 24px 56px #17203324, 0 8px 20px #315B9B14"
	TokenFontDisplay                     = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"
	TokenFontMono                        = "[\"IBM Plex Mono\",\"ui-monospace\",\"SFMono-Regular\",\"monospace\"]"
	TokenFontSans                        = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"
	TokenFontWeightBold                  = "700"
	TokenFontWeightMedium                = "500"
	TokenFontWeightRegular               = "400"
	TokenFontWeightSemibold              = "600"
	TokenLetterSpacingCaps               = "0.08em"
	TokenLetterSpacingLabel              = "0.04em"
	TokenLetterSpacingTight              = "-0.02em"
	TokenLineHeightBody                  = "1.5"
	TokenLineHeightCompact               = "1.35"
	TokenLineHeightTight                 = "1.2"
	TokenMaterialAmbientBlue             = "#07182E66"
	TokenMaterialAmbientOrange           = "#EC4E0238"
	TokenMaterialBlurOverlay             = "24px"
	TokenMaterialBlurShell               = "18px"
	TokenMaterialShellOpacityDark        = "0.94"
	TokenMaterialShellOpacityLight       = "0.97"
	TokenMaterialTopLightDark            = "#FFFFFF0A"
	TokenMaterialTopLightLight           = "#FFFFFFCC"
	TokenMotionDurationBase              = "250ms"
	TokenMotionDurationFast              = "150ms"
	TokenMotionDurationSlow              = "400ms"
	TokenMotionEaseOutExpo               = "[0.16,1,0.3,1]"
	TokenOpacityDisabled                 = "0.5"
	TokenOpacityHover                    = "0.08"
	TokenOpacityScrim                    = "0.72"
	TokenOpacitySecondary                = "0.72"
	TokenProductAgentBrowser             = "#1DB8CE"
	TokenProductAgentMemory              = "#EA5DA9"
	TokenProductAgentOrchestration       = "#4C7DFF"
	TokenProductCapture                  = "#0A84FF"
	TokenProductGateway                  = "#0079F2"
	TokenProductMangodisk                = "#FF8A3D"
	TokenProductOpenseo                  = "#20B8A6"
	TokenProductPlatform                 = "#EC4E02"
	TokenProductStore                    = "#009118"
	TokenProductToolbox                  = "#4C7DFF"
	TokenProductVault                    = "#DFA700"
	TokenProductWorkforce                = "#A170EB"
	TokenRadius2xl                       = "16px"
	TokenRadiusFull                      = "9999px"
	TokenRadiusLg                        = "8px"
	TokenRadiusMd                        = "6px"
	TokenRadiusSm                        = "4px"
	TokenRadiusXl                        = "12px"
	TokenRichnessBalancedAmbientStrength = "0.75"
	TokenRichnessBalancedBloomStrength   = "0.75"
	TokenRichnessBalancedCanvas          = "#101316"
	TokenRichnessBalancedShell           = "#171A1D"
	TokenRichnessRichAmbientStrength     = "1"
	TokenRichnessRichBloomStrength       = "1"
	TokenRichnessRichCanvas              = "#090C0F"
	TokenRichnessRichShell               = "#121518"
	TokenRichnessSoftAmbientStrength     = "0.55"
	TokenRichnessSoftBloomStrength       = "0.55"
	TokenRichnessSoftCanvas              = "#1B1E22"
	TokenRichnessSoftShell               = "#22262A"
	TokenSizeChartMinimumHeight          = "180px"
	TokenSizeChartPoint                  = "6px"
	TokenSizeControlCompact              = "28px"
	TokenSizeControlDefault              = "32px"
	TokenSizeControlTouch                = "44px"
	TokenSizeHitTargetPointer            = "28px"
	TokenSizeHitTargetTouch              = "44px"
	TokenSizeIconLg                      = "20px"
	TokenSizeIconMd                      = "16px"
	TokenSizeIconSm                      = "14px"
	TokenSizeIconXl                      = "24px"
	TokenSizePanelComfortable            = "360px"
	TokenSizePanelMinimum                = "280px"
	TokenSizePanelWide                   = "480px"
	TokenSizeRowCompact                  = "28px"
	TokenSizeRowDefault                  = "32px"
	TokenSizeRowTouch                    = "44px"
	TokenSizeShellCommandbar             = "36px"
	TokenSizeShellInspector              = "360px"
	TokenSizeShellRail                   = "48px"
	TokenSizeShellSidebar                = "196px"
	TokenSizeShellStatusbar              = "24px"
	TokenSizeShellTopbar                 = "44px"
	TokenSizeTerminalTab                 = "32px"
	TokenSpace0                          = "0px"
	TokenSpace1                          = "2px"
	TokenSpace10                         = "40px"
	TokenSpace11                         = "48px"
	TokenSpace2                          = "4px"
	TokenSpace3                          = "6px"
	TokenSpace4                          = "8px"
	TokenSpace5                          = "12px"
	TokenSpace6                          = "16px"
	TokenSpace7                          = "20px"
	TokenSpace8                          = "24px"
	TokenSpace9                          = "32px"
	TokenStrokeActive                    = "2px"
	TokenStrokeChart                     = "2px"
	TokenStrokeFocus                     = "2px"
	TokenStrokeHairline                  = "1px"
	TokenThemeDarkBorderDefault          = "#3A3E42"
	TokenThemeDarkBorderStrong           = "#4C4F52"
	TokenThemeDarkBorderSubtle           = "#272A2C"
	TokenThemeDarkCanvas                 = "#101316"
	TokenThemeDarkInkPrimary             = "#E6E8EB"
	TokenThemeDarkInkSecondary           = "#A1A8B1"
	TokenThemeDarkInkTertiary            = "#7E8792"
	TokenThemeDarkInset                  = "#14171A"
	TokenThemeDarkOverlay                = "#24282D"
	TokenThemeDarkRaised                 = "#1D2125"
	TokenThemeDarkShell                  = "#171A1D"
	TokenThemeLightBorderDefault         = "#CDD2D9"
	TokenThemeLightBorderStrong          = "#B9C0C9"
	TokenThemeLightBorderSubtle          = "#E0E3E8"
	TokenThemeLightCanvas                = "#ECEDEF"
	TokenThemeLightInkPrimary            = "#22252A"
	TokenThemeLightInkSecondary          = "#6B717A"
	TokenThemeLightInkTertiary           = "#858C96"
	TokenThemeLightInset                 = "#F2F4F7"
	TokenThemeLightOverlay               = "#FFFFFF"
	TokenThemeLightRaised                = "#FFFFFF"
	TokenThemeLightShell                 = "#F8F9FB"
	TokenTypeBody                        = "15px"
	TokenTypeBodyLg                      = "17px"
	TokenTypeBodySm                      = "13px"
	TokenTypeCaption                     = "11px"
	TokenTypeConsole                     = "12.5px"
	TokenTypeConsoleSm                   = "11px"
	TokenTypeDisplay                     = "40px"
	TokenTypeH1                          = "32px"
	TokenTypeH2                          = "24px"
	TokenTypeH3                          = "20px"
	TokenTypeH4                          = "18px"
)

var All = map[string]string{
	"breakpoint.compact-max":             TokenBreakpointCompactMax,
	"breakpoint.standard-min":            TokenBreakpointStandardMin,
	"breakpoint.ultrawide-min":           TokenBreakpointUltrawideMin,
	"breakpoint.wide-min":                TokenBreakpointWideMin,
	"color.accent.default":               TokenColorAccentDefault,
	"color.accent.emphasis":              TokenColorAccentEmphasis,
	"color.accent.fg":                    TokenColorAccentFg,
	"color.accent.muted":                 TokenColorAccentMuted,
	"color.accent.subtle":                TokenColorAccentSubtle,
	"color.bg.base":                      TokenColorBgBase,
	"color.bg.elevated":                  TokenColorBgElevated,
	"color.bg.overlay":                   TokenColorBgOverlay,
	"color.bg.subtle":                    TokenColorBgSubtle,
	"color.bg.surface":                   TokenColorBgSurface,
	"color.blue.100":                     TokenColorBlue100,
	"color.blue.200":                     TokenColorBlue200,
	"color.blue.300":                     TokenColorBlue300,
	"color.blue.400":                     TokenColorBlue400,
	"color.blue.50":                      TokenColorBlue50,
	"color.blue.500":                     TokenColorBlue500,
	"color.blue.600":                     TokenColorBlue600,
	"color.blue.700":                     TokenColorBlue700,
	"color.blue.800":                     TokenColorBlue800,
	"color.blue.900":                     TokenColorBlue900,
	"color.border.default":               TokenColorBorderDefault,
	"color.border.dimmer":                TokenColorBorderDimmer,
	"color.border.dimmest":               TokenColorBorderDimmest,
	"color.border.stronger":              TokenColorBorderStronger,
	"color.border.strongest":             TokenColorBorderStrongest,
	"color.brand.orange":                 TokenColorBrandOrange,
	"color.brand.orange-muted":           TokenColorBrandOrangeMuted,
	"color.chart.axis":                   TokenColorChartAxis,
	"color.chart.grid":                   TokenColorChartGrid,
	"color.chart.plot":                   TokenColorChartPlot,
	"color.chart.selection":              TokenColorChartSelection,
	"color.chart.series-1":               TokenColorChartSeries1,
	"color.chart.series-2":               TokenColorChartSeries2,
	"color.chart.series-3":               TokenColorChartSeries3,
	"color.chart.series-4":               TokenColorChartSeries4,
	"color.chart.series-5":               TokenColorChartSeries5,
	"color.chart.series-6":               TokenColorChartSeries6,
	"color.chart.series-7":               TokenColorChartSeries7,
	"color.chart.series-8":               TokenColorChartSeries8,
	"color.desk.agentic":                 TokenColorDeskAgentic,
	"color.desk.developer":               TokenColorDeskDeveloper,
	"color.desk.files":                   TokenColorDeskFiles,
	"color.desk.projects":                TokenColorDeskProjects,
	"color.desk.sessions":                TokenColorDeskSessions,
	"color.desk.system":                  TokenColorDeskSystem,
	"color.interactive.blue":             TokenColorInteractiveBlue,
	"color.interactive.focus":            TokenColorInteractiveFocus,
	"color.semantic.danger":              TokenColorSemanticDanger,
	"color.semantic.danger-bg":           TokenColorSemanticDangerBg,
	"color.semantic.danger-line":         TokenColorSemanticDangerLine,
	"color.semantic.info":                TokenColorSemanticInfo,
	"color.semantic.info-bg":             TokenColorSemanticInfoBg,
	"color.semantic.info-line":           TokenColorSemanticInfoLine,
	"color.semantic.success":             TokenColorSemanticSuccess,
	"color.semantic.success-bg":          TokenColorSemanticSuccessBg,
	"color.semantic.success-line":        TokenColorSemanticSuccessLine,
	"color.semantic.success-muted":       TokenColorSemanticSuccessMuted,
	"color.semantic.warning":             TokenColorSemanticWarning,
	"color.semantic.warning-bg":          TokenColorSemanticWarningBg,
	"color.semantic.warning-line":        TokenColorSemanticWarningLine,
	"color.text.disabled":                TokenColorTextDisabled,
	"color.text.on-brand":                TokenColorTextOnBrand,
	"color.text.primary":                 TokenColorTextPrimary,
	"color.text.secondary":               TokenColorTextSecondary,
	"color.text.tertiary":                TokenColorTextTertiary,
	"depth.attention-glow":               TokenDepthAttentionGlow,
	"depth.focus-glow":                   TokenDepthFocusGlow,
	"depth.raised-dark":                  TokenDepthRaisedDark,
	"depth.raised-light":                 TokenDepthRaisedLight,
	"depth.shell-dark":                   TokenDepthShellDark,
	"depth.shell-light":                  TokenDepthShellLight,
	"font.display":                       TokenFontDisplay,
	"font.mono":                          TokenFontMono,
	"font.sans":                          TokenFontSans,
	"fontWeight.bold":                    TokenFontWeightBold,
	"fontWeight.medium":                  TokenFontWeightMedium,
	"fontWeight.regular":                 TokenFontWeightRegular,
	"fontWeight.semibold":                TokenFontWeightSemibold,
	"letterSpacing.caps":                 TokenLetterSpacingCaps,
	"letterSpacing.label":                TokenLetterSpacingLabel,
	"letterSpacing.tight":                TokenLetterSpacingTight,
	"lineHeight.body":                    TokenLineHeightBody,
	"lineHeight.compact":                 TokenLineHeightCompact,
	"lineHeight.tight":                   TokenLineHeightTight,
	"material.ambient-blue":              TokenMaterialAmbientBlue,
	"material.ambient-orange":            TokenMaterialAmbientOrange,
	"material.blur-overlay":              TokenMaterialBlurOverlay,
	"material.blur-shell":                TokenMaterialBlurShell,
	"material.shell-opacity-dark":        TokenMaterialShellOpacityDark,
	"material.shell-opacity-light":       TokenMaterialShellOpacityLight,
	"material.top-light-dark":            TokenMaterialTopLightDark,
	"material.top-light-light":           TokenMaterialTopLightLight,
	"motion.duration-base":               TokenMotionDurationBase,
	"motion.duration-fast":               TokenMotionDurationFast,
	"motion.duration-slow":               TokenMotionDurationSlow,
	"motion.ease-out-expo":               TokenMotionEaseOutExpo,
	"opacity.disabled":                   TokenOpacityDisabled,
	"opacity.hover":                      TokenOpacityHover,
	"opacity.scrim":                      TokenOpacityScrim,
	"opacity.secondary":                  TokenOpacitySecondary,
	"product.agent-browser":              TokenProductAgentBrowser,
	"product.agent-memory":               TokenProductAgentMemory,
	"product.agent-orchestration":        TokenProductAgentOrchestration,
	"product.capture":                    TokenProductCapture,
	"product.gateway":                    TokenProductGateway,
	"product.mangodisk":                  TokenProductMangodisk,
	"product.openseo":                    TokenProductOpenseo,
	"product.platform":                   TokenProductPlatform,
	"product.store":                      TokenProductStore,
	"product.toolbox":                    TokenProductToolbox,
	"product.vault":                      TokenProductVault,
	"product.workforce":                  TokenProductWorkforce,
	"radius.2xl":                         TokenRadius2xl,
	"radius.full":                        TokenRadiusFull,
	"radius.lg":                          TokenRadiusLg,
	"radius.md":                          TokenRadiusMd,
	"radius.sm":                          TokenRadiusSm,
	"radius.xl":                          TokenRadiusXl,
	"richness.balanced.ambient-strength": TokenRichnessBalancedAmbientStrength,
	"richness.balanced.bloom-strength":   TokenRichnessBalancedBloomStrength,
	"richness.balanced.canvas":           TokenRichnessBalancedCanvas,
	"richness.balanced.shell":            TokenRichnessBalancedShell,
	"richness.rich.ambient-strength":     TokenRichnessRichAmbientStrength,
	"richness.rich.bloom-strength":       TokenRichnessRichBloomStrength,
	"richness.rich.canvas":               TokenRichnessRichCanvas,
	"richness.rich.shell":                TokenRichnessRichShell,
	"richness.soft.ambient-strength":     TokenRichnessSoftAmbientStrength,
	"richness.soft.bloom-strength":       TokenRichnessSoftBloomStrength,
	"richness.soft.canvas":               TokenRichnessSoftCanvas,
	"richness.soft.shell":                TokenRichnessSoftShell,
	"size.chart.minimum-height":          TokenSizeChartMinimumHeight,
	"size.chart.point":                   TokenSizeChartPoint,
	"size.control.compact":               TokenSizeControlCompact,
	"size.control.default":               TokenSizeControlDefault,
	"size.control.touch":                 TokenSizeControlTouch,
	"size.hit-target.pointer":            TokenSizeHitTargetPointer,
	"size.hit-target.touch":              TokenSizeHitTargetTouch,
	"size.icon.lg":                       TokenSizeIconLg,
	"size.icon.md":                       TokenSizeIconMd,
	"size.icon.sm":                       TokenSizeIconSm,
	"size.icon.xl":                       TokenSizeIconXl,
	"size.panel.comfortable":             TokenSizePanelComfortable,
	"size.panel.minimum":                 TokenSizePanelMinimum,
	"size.panel.wide":                    TokenSizePanelWide,
	"size.row.compact":                   TokenSizeRowCompact,
	"size.row.default":                   TokenSizeRowDefault,
	"size.row.touch":                     TokenSizeRowTouch,
	"size.shell.commandbar":              TokenSizeShellCommandbar,
	"size.shell.inspector":               TokenSizeShellInspector,
	"size.shell.rail":                    TokenSizeShellRail,
	"size.shell.sidebar":                 TokenSizeShellSidebar,
	"size.shell.statusbar":               TokenSizeShellStatusbar,
	"size.shell.topbar":                  TokenSizeShellTopbar,
	"size.terminal.tab":                  TokenSizeTerminalTab,
	"space.0":                            TokenSpace0,
	"space.1":                            TokenSpace1,
	"space.10":                           TokenSpace10,
	"space.11":                           TokenSpace11,
	"space.2":                            TokenSpace2,
	"space.3":                            TokenSpace3,
	"space.4":                            TokenSpace4,
	"space.5":                            TokenSpace5,
	"space.6":                            TokenSpace6,
	"space.7":                            TokenSpace7,
	"space.8":                            TokenSpace8,
	"space.9":                            TokenSpace9,
	"stroke.active":                      TokenStrokeActive,
	"stroke.chart":                       TokenStrokeChart,
	"stroke.focus":                       TokenStrokeFocus,
	"stroke.hairline":                    TokenStrokeHairline,
	"theme.dark.border-default":          TokenThemeDarkBorderDefault,
	"theme.dark.border-strong":           TokenThemeDarkBorderStrong,
	"theme.dark.border-subtle":           TokenThemeDarkBorderSubtle,
	"theme.dark.canvas":                  TokenThemeDarkCanvas,
	"theme.dark.ink-primary":             TokenThemeDarkInkPrimary,
	"theme.dark.ink-secondary":           TokenThemeDarkInkSecondary,
	"theme.dark.ink-tertiary":            TokenThemeDarkInkTertiary,
	"theme.dark.inset":                   TokenThemeDarkInset,
	"theme.dark.overlay":                 TokenThemeDarkOverlay,
	"theme.dark.raised":                  TokenThemeDarkRaised,
	"theme.dark.shell":                   TokenThemeDarkShell,
	"theme.light.border-default":         TokenThemeLightBorderDefault,
	"theme.light.border-strong":          TokenThemeLightBorderStrong,
	"theme.light.border-subtle":          TokenThemeLightBorderSubtle,
	"theme.light.canvas":                 TokenThemeLightCanvas,
	"theme.light.ink-primary":            TokenThemeLightInkPrimary,
	"theme.light.ink-secondary":          TokenThemeLightInkSecondary,
	"theme.light.ink-tertiary":           TokenThemeLightInkTertiary,
	"theme.light.inset":                  TokenThemeLightInset,
	"theme.light.overlay":                TokenThemeLightOverlay,
	"theme.light.raised":                 TokenThemeLightRaised,
	"theme.light.shell":                  TokenThemeLightShell,
	"type.body":                          TokenTypeBody,
	"type.body-lg":                       TokenTypeBodyLg,
	"type.body-sm":                       TokenTypeBodySm,
	"type.caption":                       TokenTypeCaption,
	"type.console":                       TokenTypeConsole,
	"type.console-sm":                    TokenTypeConsoleSm,
	"type.display":                       TokenTypeDisplay,
	"type.h1":                            TokenTypeH1,
	"type.h2":                            TokenTypeH2,
	"type.h3":                            TokenTypeH3,
	"type.h4":                            TokenTypeH4,
}
