export const EVENT_NAMES = {
  cleanupScanProgress: 'cleanup-scan-progress',
  cleanupExecutionProgress: 'cleanup-execution-progress',
  analysisProgress: 'analysis-progress',
  largeFilesProgress: 'large-files-progress',
  duplicateFilesProgress: 'duplicate-files-progress',
  duplicateFileGroups: 'duplicate-files-groups',
  applicationUninstallProgress: 'application-uninstall-progress',
  applicationUninstallExecutionProgress: 'application-uninstall-execution-progress',
} as const;

export const LOG_DOMAINS = {
  applicationShell: 'application-shell',
  appUpdate: 'app-update',
  applicationUninstall: 'application-uninstall',
  analysis: 'analysis',
  chat: 'chat',
  cleanup: 'cleanup',
  duplicateFiles: 'duplicate-files',
  folderPicker: 'folder-picker',
  history: 'history',
  largeFiles: 'large-files',
  macosPermissions: 'macos-permissions',
  settings: 'settings',
  startup: 'startup',
  storageScope: 'storage-scope',
} as const;

export const LOG_EVENTS = {
  operationDeferred: 'operation_deferred',
  operationFailed: 'operation_failed',
  chatEventSequenceGap: 'chat_event_sequence_gap',
  chatPromptFailed: 'chat_prompt_failed',
  chatProviderProbeFailed: 'chat_provider_probe_failed',
  chatSessionEnded: 'chat_session_ended',
  chatSessionEventDropped: 'chat_session_event_dropped',
  chatSessionStartFailed: 'chat_session_start_failed',
  updateAvailable: 'update_available',
  updateCheckFailed: 'update_check_failed',
  updateCheckStarted: 'update_check_started',
  updateDownloadCompleted: 'update_download_completed',
  updateDownloadFailed: 'update_download_failed',
  updateDownloadStarted: 'update_download_started',
  updateDistributionReadFailed: 'update_distribution_read_failed',
  updateInstallCompleted: 'update_install_completed',
  updateInstallStarted: 'update_install_started',
  updateInstallFailed: 'update_install_failed',
  updateRestartFailed: 'update_restart_failed',
  updateMetadataUnavailable: 'update_metadata_unavailable',
  updateManualDownloadFailed: 'update_manual_download_failed',
  updateManualDownloadOpened: 'update_manual_download_opened',
  updateNotAvailable: 'update_not_available',
  updateVersionReadFailed: 'update_version_read_failed',
  deleteCompletedWithFailures: 'delete_completed_with_failures',
  diskRefreshFailed: 'disk_refresh_failed',
  volumeSelectionRefreshFailed: 'volume_selection_refresh_failed',
  historyRefreshFailed: 'history_refresh_failed',
  analysisCacheSyncedAfterDelete: 'cache_synced_after_delete',
  droppedFolderValidationFailed: 'dropped_folder_validation_failed',
  folderDialogFailed: 'folder_dialog_failed',
  nativeFolderDropUnavailable: 'native_folder_drop_unavailable',
  standardScanFoldersLoadFailed: 'standard_scan_folders_load_failed',
  startupSystemSettingsOpenRequested: 'startup_system_settings_open_requested',
  permissionObservationClearFailed: 'permission_observation_clear_failed',
  permissionObservationInvalid: 'permission_observation_invalid',
  permissionObservationLoadFailed: 'permission_observation_load_failed',
  permissionObservationSaved: 'permission_observation_saved',
  permissionObservationSaveFailed: 'permission_observation_save_failed',
  privacySettingsOpenRequested: 'privacy_settings_open_requested',
  savedSettingsClearFailed: 'saved_settings_clear_failed',
  savedSettingsInvalid: 'saved_settings_invalid',
  savedSettingsLoadFailed: 'saved_settings_load_failed',
  savedSettingsSaveFailed: 'saved_settings_save_failed',
  staleScanResultIgnored: 'stale_scan_result_ignored',
  storageScopePreferencesClearFailed: 'preferences_clear_failed',
  storageScopePreferencesInvalid: 'preferences_invalid',
  storageScopePreferencesLoadFailed: 'preferences_load_failed',
  storageScopePreferencesSaveFailed: 'preferences_save_failed',
  storageScopeValidationFailed: 'folder_validation_failed',
} as const;
