// Code generated by build/generate.mjs; DO NOT EDIT.
// Source: foundation/tokens.json
// Source SHA-256: 9c3f4a3bc1ae86e4f8e7a480c1b368dc029799a78dac2d1dfd5e4c8a88fd3a10

pub const TOKEN_SOURCE_SHA256: &str = "9c3f4a3bc1ae86e4f8e7a480c1b368dc029799a78dac2d1dfd5e4c8a88fd3a10";

pub const BREAKPOINT_COMPACT_MAX: &str = "719px";
pub const BREAKPOINT_STANDARD_MIN: &str = "720px";
pub const BREAKPOINT_ULTRAWIDE_MIN: &str = "1600px";
pub const BREAKPOINT_WIDE_MIN: &str = "1200px";
pub const COLOR_ACCENT_DEFAULT: &str = "#047BF4";
pub const COLOR_ACCENT_EMPHASIS: &str = "#468CE8";
pub const COLOR_ACCENT_FG: &str = "#E8F1FB";
pub const COLOR_ACCENT_MUTED: &str = "#255DA5";
pub const COLOR_ACCENT_SUBTLE: &str = "#193356";
pub const COLOR_BG_BASE: &str = "#101316";
pub const COLOR_BG_ELEVATED: &str = "#24282D";
pub const COLOR_BG_OVERLAY: &str = "#2B3036";
pub const COLOR_BG_SUBTLE: &str = "#171A1D";
pub const COLOR_BG_SURFACE: &str = "#1D2125";
pub const COLOR_BLUE_100: &str = "#0E2037";
pub const COLOR_BLUE_200: &str = "#193356";
pub const COLOR_BLUE_300: &str = "#1F487C";
pub const COLOR_BLUE_400: &str = "#255DA5";
pub const COLOR_BLUE_50: &str = "#071221";
pub const COLOR_BLUE_500: &str = "#047BF4";
pub const COLOR_BLUE_600: &str = "#468CE8";
pub const COLOR_BLUE_700: &str = "#71A7EF";
pub const COLOR_BLUE_800: &str = "#9CC0F1";
pub const COLOR_BLUE_900: &str = "#C7D9F2";
pub const COLOR_BORDER_DEFAULT: &str = "#3A3E42";
pub const COLOR_BORDER_DIMMER: &str = "#303438";
pub const COLOR_BORDER_DIMMEST: &str = "#272A2C";
pub const COLOR_BORDER_STRONGER: &str = "#44484C";
pub const COLOR_BORDER_STRONGEST: &str = "#4C4F52";
pub const COLOR_BRAND_ORANGE: &str = "#EC4E02";
pub const COLOR_BRAND_ORANGE_MUTED: &str = "#D96D00";
pub const COLOR_CHART_AXIS: &str = "#A2A8B2";
pub const COLOR_CHART_GRID: &str = "#31343F";
pub const COLOR_CHART_PLOT: &str = "#1A1C25";
pub const COLOR_CHART_SELECTION: &str = "#468CE8";
pub const COLOR_CHART_SERIES_1: &str = "#047BF4";
pub const COLOR_CHART_SERIES_2: &str = "#1DB8CE";
pub const COLOR_CHART_SERIES_3: &str = "#A170EB";
pub const COLOR_CHART_SERIES_4: &str = "#EA5DA9";
pub const COLOR_CHART_SERIES_5: &str = "#EC4E02";
pub const COLOR_CHART_SERIES_6: &str = "#029219";
pub const COLOR_CHART_SERIES_7: &str = "#DFA700";
pub const COLOR_CHART_SERIES_8: &str = "#E52222";
pub const COLOR_DESK_AGENTIC: &str = "#1B3060";
pub const COLOR_DESK_DEVELOPER: &str = "#2F2D55";
pub const COLOR_DESK_FILES: &str = "#013752";
pub const COLOR_DESK_PROJECTS: &str = "#282F56";
pub const COLOR_DESK_SESSIONS: &str = "#193356";
pub const COLOR_DESK_SYSTEM: &str = "#1D354B";
pub const COLOR_INTERACTIVE_BLUE: &str = "#047BF4";
pub const COLOR_INTERACTIVE_FOCUS: &str = "#71A7EF";
pub const COLOR_SEMANTIC_DANGER: &str = "#E52222";
pub const COLOR_SEMANTIC_DANGER_BG: &str = "#2A1212";
pub const COLOR_SEMANTIC_DANGER_INK: &str = "#D6695D";
pub const COLOR_SEMANTIC_DANGER_LINE: &str = "#7A2424";
pub const COLOR_SEMANTIC_INFO: &str = "#1DB8CE";
pub const COLOR_SEMANTIC_INFO_BG: &str = "#0C2226";
pub const COLOR_SEMANTIC_INFO_INK: &str = "#0097AD";
pub const COLOR_SEMANTIC_INFO_LINE: &str = "#1A5A64";
pub const COLOR_SEMANTIC_SUCCESS: &str = "#029219";
pub const COLOR_SEMANTIC_SUCCESS_BG: &str = "#0C2414";
pub const COLOR_SEMANTIC_SUCCESS_INK: &str = "#4A9A4A";
pub const COLOR_SEMANTIC_SUCCESS_LINE: &str = "#165C22";
pub const COLOR_SEMANTIC_SUCCESS_MUTED: &str = "#007012";
pub const COLOR_SEMANTIC_WARNING: &str = "#DFA700";
pub const COLOR_SEMANTIC_WARNING_BG: &str = "#241E0C";
pub const COLOR_SEMANTIC_WARNING_INK: &str = "#B18100";
pub const COLOR_SEMANTIC_WARNING_LINE: &str = "#6B5A14";
pub const COLOR_TEXT_DISABLED: &str = "#626A74";
pub const COLOR_TEXT_ON_BRAND: &str = "#101316";
pub const COLOR_TEXT_ON_INTERACTIVE: &str = "#101316";
pub const COLOR_TEXT_PRIMARY: &str = "#E6E8EB";
pub const COLOR_TEXT_SECONDARY: &str = "#A1A8B1";
pub const COLOR_TEXT_TERTIARY: &str = "#7E8792";
pub const DEPTH_ATTENTION_GLOW: &str = "0 0 20px #EC4E0238";
pub const DEPTH_FOCUS_GLOW: &str = "0 0 0 1px #1B84F3, 0 0 24px #1B84F34D";
pub const DEPTH_RAISED_DARK: &str = "inset 0 1px 0 #FFFFFF08, 0 8px 20px #05080D66";
pub const DEPTH_RAISED_LIGHT: &str = "inset 0 1px 0 #FFFFFFE6, 0 8px 20px #17203317";
pub const DEPTH_SHELL_DARK: &str = "inset 0 1px 0 #FFFFFF0A, 0 24px 56px #05080DB8, 0 8px 20px #07182E66";
pub const DEPTH_SHELL_LIGHT: &str = "inset 0 1px 0 #FFFFFFCC, 0 24px 56px #17203324, 0 8px 20px #315B9B14";
pub const FONT_DISPLAY: &str = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]";
pub const FONT_MONO: &str = "[\"IBM Plex Mono\",\"ui-monospace\",\"SFMono-Regular\",\"monospace\"]";
pub const FONT_SANS: &str = "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]";
pub const FONTWEIGHT_BOLD: &str = "700";
pub const FONTWEIGHT_MEDIUM: &str = "500";
pub const FONTWEIGHT_REGULAR: &str = "400";
pub const FONTWEIGHT_SEMIBOLD: &str = "600";
pub const LETTERSPACING_CAPS: &str = "0.08em";
pub const LETTERSPACING_LABEL: &str = "0.04em";
pub const LETTERSPACING_TIGHT: &str = "-0.02em";
pub const LINEHEIGHT_BODY: &str = "1.5";
pub const LINEHEIGHT_COMPACT: &str = "1.35";
pub const LINEHEIGHT_TIGHT: &str = "1.2";
pub const MATERIAL_AMBIENT_BLUE: &str = "#07182E66";
pub const MATERIAL_AMBIENT_ORANGE: &str = "#EC4E0238";
pub const MATERIAL_BLUR_OVERLAY: &str = "24px";
pub const MATERIAL_BLUR_SHELL: &str = "18px";
pub const MATERIAL_SHELL_OPACITY_DARK: &str = "0.94";
pub const MATERIAL_SHELL_OPACITY_LIGHT: &str = "0.97";
pub const MATERIAL_TOP_LIGHT_DARK: &str = "#FFFFFF0A";
pub const MATERIAL_TOP_LIGHT_LIGHT: &str = "#FFFFFFCC";
pub const MOTION_DURATION_BASE: &str = "250ms";
pub const MOTION_DURATION_FAST: &str = "150ms";
pub const MOTION_DURATION_SLOW: &str = "400ms";
pub const MOTION_EASE_OUT_EXPO: &str = "[0.16,1,0.3,1]";
pub const OPACITY_DISABLED: &str = "0.5";
pub const OPACITY_HOVER: &str = "0.08";
pub const OPACITY_SCRIM: &str = "0.72";
pub const OPACITY_SECONDARY: &str = "0.72";
pub const PRODUCT_AGENT_BROWSER: &str = "#1DB6A5";
pub const PRODUCT_AGENT_MAIL: &str = "#7F95FE";
pub const PRODUCT_AGENT_MEMORY: &str = "#FA618E";
pub const PRODUCT_AGENT_ORCHESTRATION: &str = "#C1BBFF";
pub const PRODUCT_CAPTURE: &str = "#6AD3FF";
pub const PRODUCT_GATEWAY: &str = "#047BF4";
pub const PRODUCT_MANGODISK: &str = "#FEAF7B";
pub const PRODUCT_MARKETPLACE: &str = "#D2CA06";
pub const PRODUCT_OPENSEO: &str = "#19E5AD";
pub const PRODUCT_PASSPORT: &str = "#E26ACE";
pub const PRODUCT_PLATFORM: &str = "#EC4E02";
pub const PRODUCT_STORE: &str = "#8DAE00";
pub const PRODUCT_TOOLBOX: &str = "#B97BFD";
pub const PRODUCT_VAULT: &str = "#D98A0D";
pub const PRODUCT_WORKFORCE: &str = "#FEA3D0";
pub const RADIUS_2XL: &str = "16px";
pub const RADIUS_FULL: &str = "9999px";
pub const RADIUS_LG: &str = "8px";
pub const RADIUS_MD: &str = "6px";
pub const RADIUS_SM: &str = "4px";
pub const RADIUS_XL: &str = "12px";
pub const RICHNESS_BALANCED_AMBIENT_STRENGTH: &str = "0.75";
pub const RICHNESS_BALANCED_BLOOM_STRENGTH: &str = "0.75";
pub const RICHNESS_BALANCED_CANVAS: &str = "#101316";
pub const RICHNESS_BALANCED_SHELL: &str = "#171A1D";
pub const RICHNESS_RICH_AMBIENT_STRENGTH: &str = "1";
pub const RICHNESS_RICH_BLOOM_STRENGTH: &str = "1";
pub const RICHNESS_RICH_CANVAS: &str = "#090C0F";
pub const RICHNESS_RICH_SHELL: &str = "#121518";
pub const RICHNESS_SOFT_AMBIENT_STRENGTH: &str = "0.55";
pub const RICHNESS_SOFT_BLOOM_STRENGTH: &str = "0.55";
pub const RICHNESS_SOFT_CANVAS: &str = "#1B1E22";
pub const RICHNESS_SOFT_SHELL: &str = "#22262A";
pub const SIZE_CHART_MINIMUM_HEIGHT: &str = "180px";
pub const SIZE_CHART_POINT: &str = "6px";
pub const SIZE_CONTROL_COMPACT: &str = "28px";
pub const SIZE_CONTROL_DEFAULT: &str = "32px";
pub const SIZE_CONTROL_TOUCH: &str = "44px";
pub const SIZE_HIT_TARGET_POINTER: &str = "28px";
pub const SIZE_HIT_TARGET_TOUCH: &str = "44px";
pub const SIZE_ICON_LG: &str = "20px";
pub const SIZE_ICON_MD: &str = "16px";
pub const SIZE_ICON_SM: &str = "14px";
pub const SIZE_ICON_XL: &str = "24px";
pub const SIZE_PANEL_COMFORTABLE: &str = "360px";
pub const SIZE_PANEL_MINIMUM: &str = "280px";
pub const SIZE_PANEL_WIDE: &str = "480px";
pub const SIZE_ROW_COMPACT: &str = "28px";
pub const SIZE_ROW_DEFAULT: &str = "32px";
pub const SIZE_ROW_TOUCH: &str = "44px";
pub const SIZE_SHELL_COMMANDBAR: &str = "36px";
pub const SIZE_SHELL_INSPECTOR: &str = "360px";
pub const SIZE_SHELL_RAIL: &str = "48px";
pub const SIZE_SHELL_SIDEBAR: &str = "196px";
pub const SIZE_SHELL_STATUSBAR: &str = "24px";
pub const SIZE_SHELL_TOPBAR: &str = "44px";
pub const SIZE_TERMINAL_TAB: &str = "32px";
pub const SPACE_0: &str = "0px";
pub const SPACE_1: &str = "2px";
pub const SPACE_10: &str = "40px";
pub const SPACE_11: &str = "48px";
pub const SPACE_2: &str = "4px";
pub const SPACE_3: &str = "6px";
pub const SPACE_4: &str = "8px";
pub const SPACE_5: &str = "12px";
pub const SPACE_6: &str = "16px";
pub const SPACE_7: &str = "20px";
pub const SPACE_8: &str = "24px";
pub const SPACE_9: &str = "32px";
pub const STROKE_ACTIVE: &str = "2px";
pub const STROKE_CHART: &str = "2px";
pub const STROKE_FOCUS: &str = "2px";
pub const STROKE_HAIRLINE: &str = "1px";
pub const THEME_DARK_BORDER_DEFAULT: &str = "#3A3E42";
pub const THEME_DARK_BORDER_STRONG: &str = "#4C4F52";
pub const THEME_DARK_BORDER_SUBTLE: &str = "#272A2C";
pub const THEME_DARK_CANVAS: &str = "#101316";
pub const THEME_DARK_INK_PRIMARY: &str = "#E6E8EB";
pub const THEME_DARK_INK_SECONDARY: &str = "#A1A8B1";
pub const THEME_DARK_INK_TERTIARY: &str = "#7E8792";
pub const THEME_DARK_INSET: &str = "#14171A";
pub const THEME_DARK_OVERLAY: &str = "#24282D";
pub const THEME_DARK_RAISED: &str = "#1D2125";
pub const THEME_DARK_SHELL: &str = "#171A1D";
pub const THEME_LIGHT_BORDER_DEFAULT: &str = "#CDD2D9";
pub const THEME_LIGHT_BORDER_DIMMER: &str = "#D6DAE0";
pub const THEME_LIGHT_BORDER_STRONG: &str = "#B9C0C9";
pub const THEME_LIGHT_BORDER_STRONGER: &str = "#C3C9D1";
pub const THEME_LIGHT_BORDER_SUBTLE: &str = "#E0E3E8";
pub const THEME_LIGHT_CANVAS: &str = "#ECEDEF";
pub const THEME_LIGHT_DANGER: &str = "#B93F36";
pub const THEME_LIGHT_DANGER_BG: &str = "#FFECE8";
pub const THEME_LIGHT_DANGER_INK: &str = "#B93F36";
pub const THEME_LIGHT_DANGER_LINE: &str = "#F2A89E";
pub const THEME_LIGHT_INFO: &str = "#007489";
pub const THEME_LIGHT_INFO_BG: &str = "#DEF9FF";
pub const THEME_LIGHT_INFO_INK: &str = "#007489";
pub const THEME_LIGHT_INFO_LINE: &str = "#73CEDE";
pub const THEME_LIGHT_INK_DISABLED: &str = "#9AA1AB";
pub const THEME_LIGHT_INK_ON_INTERACTIVE: &str = "#F4F7FD";
pub const THEME_LIGHT_INK_PRIMARY: &str = "#22252A";
pub const THEME_LIGHT_INK_SECONDARY: &str = "#6B717A";
pub const THEME_LIGHT_INK_TERTIARY: &str = "#858C96";
pub const THEME_LIGHT_INSET: &str = "#F2F4F7";
pub const THEME_LIGHT_INTERACTIVE_BLUE: &str = "#255DA5";
pub const THEME_LIGHT_OVERLAY: &str = "#FDFDFF";
pub const THEME_LIGHT_RAISED: &str = "#FBFCFE";
pub const THEME_LIGHT_SHELL: &str = "#F8F9FB";
pub const THEME_LIGHT_SUCCESS: &str = "#0F7B1A";
pub const THEME_LIGHT_SUCCESS_BG: &str = "#E8F9E7";
pub const THEME_LIGHT_SUCCESS_INK: &str = "#0F7B1A";
pub const THEME_LIGHT_SUCCESS_LINE: &str = "#9BCD99";
pub const THEME_LIGHT_WARNING: &str = "#945F00";
pub const THEME_LIGHT_WARNING_BG: &str = "#FDF2DD";
pub const THEME_LIGHT_WARNING_INK: &str = "#945F00";
pub const THEME_LIGHT_WARNING_LINE: &str = "#D9B979";
pub const TYPE_BODY: &str = "15px";
pub const TYPE_BODY_LG: &str = "17px";
pub const TYPE_BODY_SM: &str = "13px";
pub const TYPE_CAPTION: &str = "11px";
pub const TYPE_CONSOLE: &str = "12.5px";
pub const TYPE_CONSOLE_SM: &str = "11px";
pub const TYPE_DISPLAY: &str = "40px";
pub const TYPE_H1: &str = "32px";
pub const TYPE_H2: &str = "24px";
pub const TYPE_H3: &str = "20px";
pub const TYPE_H4: &str = "18px";

pub const ALL: &[(&str, &str)] = &[
    ("breakpoint.compact-max", "719px"),
    ("breakpoint.standard-min", "720px"),
    ("breakpoint.ultrawide-min", "1600px"),
    ("breakpoint.wide-min", "1200px"),
    ("color.accent.default", "#047BF4"),
    ("color.accent.emphasis", "#468CE8"),
    ("color.accent.fg", "#E8F1FB"),
    ("color.accent.muted", "#255DA5"),
    ("color.accent.subtle", "#193356"),
    ("color.bg.base", "#101316"),
    ("color.bg.elevated", "#24282D"),
    ("color.bg.overlay", "#2B3036"),
    ("color.bg.subtle", "#171A1D"),
    ("color.bg.surface", "#1D2125"),
    ("color.blue.100", "#0E2037"),
    ("color.blue.200", "#193356"),
    ("color.blue.300", "#1F487C"),
    ("color.blue.400", "#255DA5"),
    ("color.blue.50", "#071221"),
    ("color.blue.500", "#047BF4"),
    ("color.blue.600", "#468CE8"),
    ("color.blue.700", "#71A7EF"),
    ("color.blue.800", "#9CC0F1"),
    ("color.blue.900", "#C7D9F2"),
    ("color.border.default", "#3A3E42"),
    ("color.border.dimmer", "#303438"),
    ("color.border.dimmest", "#272A2C"),
    ("color.border.stronger", "#44484C"),
    ("color.border.strongest", "#4C4F52"),
    ("color.brand.orange", "#EC4E02"),
    ("color.brand.orange-muted", "#D96D00"),
    ("color.chart.axis", "#A2A8B2"),
    ("color.chart.grid", "#31343F"),
    ("color.chart.plot", "#1A1C25"),
    ("color.chart.selection", "#468CE8"),
    ("color.chart.series-1", "#047BF4"),
    ("color.chart.series-2", "#1DB8CE"),
    ("color.chart.series-3", "#A170EB"),
    ("color.chart.series-4", "#EA5DA9"),
    ("color.chart.series-5", "#EC4E02"),
    ("color.chart.series-6", "#029219"),
    ("color.chart.series-7", "#DFA700"),
    ("color.chart.series-8", "#E52222"),
    ("color.desk.agentic", "#1B3060"),
    ("color.desk.developer", "#2F2D55"),
    ("color.desk.files", "#013752"),
    ("color.desk.projects", "#282F56"),
    ("color.desk.sessions", "#193356"),
    ("color.desk.system", "#1D354B"),
    ("color.interactive.blue", "#047BF4"),
    ("color.interactive.focus", "#71A7EF"),
    ("color.semantic.danger", "#E52222"),
    ("color.semantic.danger-bg", "#2A1212"),
    ("color.semantic.danger-ink", "#D6695D"),
    ("color.semantic.danger-line", "#7A2424"),
    ("color.semantic.info", "#1DB8CE"),
    ("color.semantic.info-bg", "#0C2226"),
    ("color.semantic.info-ink", "#0097AD"),
    ("color.semantic.info-line", "#1A5A64"),
    ("color.semantic.success", "#029219"),
    ("color.semantic.success-bg", "#0C2414"),
    ("color.semantic.success-ink", "#4A9A4A"),
    ("color.semantic.success-line", "#165C22"),
    ("color.semantic.success-muted", "#007012"),
    ("color.semantic.warning", "#DFA700"),
    ("color.semantic.warning-bg", "#241E0C"),
    ("color.semantic.warning-ink", "#B18100"),
    ("color.semantic.warning-line", "#6B5A14"),
    ("color.text.disabled", "#626A74"),
    ("color.text.on-brand", "#101316"),
    ("color.text.on-interactive", "#101316"),
    ("color.text.primary", "#E6E8EB"),
    ("color.text.secondary", "#A1A8B1"),
    ("color.text.tertiary", "#7E8792"),
    ("depth.attention-glow", "0 0 20px #EC4E0238"),
    ("depth.focus-glow", "0 0 0 1px #1B84F3, 0 0 24px #1B84F34D"),
    ("depth.raised-dark", "inset 0 1px 0 #FFFFFF08, 0 8px 20px #05080D66"),
    ("depth.raised-light", "inset 0 1px 0 #FFFFFFE6, 0 8px 20px #17203317"),
    ("depth.shell-dark", "inset 0 1px 0 #FFFFFF0A, 0 24px 56px #05080DB8, 0 8px 20px #07182E66"),
    ("depth.shell-light", "inset 0 1px 0 #FFFFFFCC, 0 24px 56px #17203324, 0 8px 20px #315B9B14"),
    ("font.display", "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"),
    ("font.mono", "[\"IBM Plex Mono\",\"ui-monospace\",\"SFMono-Regular\",\"monospace\"]"),
    ("font.sans", "[\"IBM Plex Sans\",\"ui-sans-serif\",\"system-ui\",\"-apple-system\",\"sans-serif\"]"),
    ("fontWeight.bold", "700"),
    ("fontWeight.medium", "500"),
    ("fontWeight.regular", "400"),
    ("fontWeight.semibold", "600"),
    ("letterSpacing.caps", "0.08em"),
    ("letterSpacing.label", "0.04em"),
    ("letterSpacing.tight", "-0.02em"),
    ("lineHeight.body", "1.5"),
    ("lineHeight.compact", "1.35"),
    ("lineHeight.tight", "1.2"),
    ("material.ambient-blue", "#07182E66"),
    ("material.ambient-orange", "#EC4E0238"),
    ("material.blur-overlay", "24px"),
    ("material.blur-shell", "18px"),
    ("material.shell-opacity-dark", "0.94"),
    ("material.shell-opacity-light", "0.97"),
    ("material.top-light-dark", "#FFFFFF0A"),
    ("material.top-light-light", "#FFFFFFCC"),
    ("motion.duration-base", "250ms"),
    ("motion.duration-fast", "150ms"),
    ("motion.duration-slow", "400ms"),
    ("motion.ease-out-expo", "[0.16,1,0.3,1]"),
    ("opacity.disabled", "0.5"),
    ("opacity.hover", "0.08"),
    ("opacity.scrim", "0.72"),
    ("opacity.secondary", "0.72"),
    ("product.agent-browser", "#1DB6A5"),
    ("product.agent-mail", "#7F95FE"),
    ("product.agent-memory", "#FA618E"),
    ("product.agent-orchestration", "#C1BBFF"),
    ("product.capture", "#6AD3FF"),
    ("product.gateway", "#047BF4"),
    ("product.mangodisk", "#FEAF7B"),
    ("product.marketplace", "#D2CA06"),
    ("product.openseo", "#19E5AD"),
    ("product.passport", "#E26ACE"),
    ("product.platform", "#EC4E02"),
    ("product.store", "#8DAE00"),
    ("product.toolbox", "#B97BFD"),
    ("product.vault", "#D98A0D"),
    ("product.workforce", "#FEA3D0"),
    ("radius.2xl", "16px"),
    ("radius.full", "9999px"),
    ("radius.lg", "8px"),
    ("radius.md", "6px"),
    ("radius.sm", "4px"),
    ("radius.xl", "12px"),
    ("richness.balanced.ambient-strength", "0.75"),
    ("richness.balanced.bloom-strength", "0.75"),
    ("richness.balanced.canvas", "#101316"),
    ("richness.balanced.shell", "#171A1D"),
    ("richness.rich.ambient-strength", "1"),
    ("richness.rich.bloom-strength", "1"),
    ("richness.rich.canvas", "#090C0F"),
    ("richness.rich.shell", "#121518"),
    ("richness.soft.ambient-strength", "0.55"),
    ("richness.soft.bloom-strength", "0.55"),
    ("richness.soft.canvas", "#1B1E22"),
    ("richness.soft.shell", "#22262A"),
    ("size.chart.minimum-height", "180px"),
    ("size.chart.point", "6px"),
    ("size.control.compact", "28px"),
    ("size.control.default", "32px"),
    ("size.control.touch", "44px"),
    ("size.hit-target.pointer", "28px"),
    ("size.hit-target.touch", "44px"),
    ("size.icon.lg", "20px"),
    ("size.icon.md", "16px"),
    ("size.icon.sm", "14px"),
    ("size.icon.xl", "24px"),
    ("size.panel.comfortable", "360px"),
    ("size.panel.minimum", "280px"),
    ("size.panel.wide", "480px"),
    ("size.row.compact", "28px"),
    ("size.row.default", "32px"),
    ("size.row.touch", "44px"),
    ("size.shell.commandbar", "36px"),
    ("size.shell.inspector", "360px"),
    ("size.shell.rail", "48px"),
    ("size.shell.sidebar", "196px"),
    ("size.shell.statusbar", "24px"),
    ("size.shell.topbar", "44px"),
    ("size.terminal.tab", "32px"),
    ("space.0", "0px"),
    ("space.1", "2px"),
    ("space.10", "40px"),
    ("space.11", "48px"),
    ("space.2", "4px"),
    ("space.3", "6px"),
    ("space.4", "8px"),
    ("space.5", "12px"),
    ("space.6", "16px"),
    ("space.7", "20px"),
    ("space.8", "24px"),
    ("space.9", "32px"),
    ("stroke.active", "2px"),
    ("stroke.chart", "2px"),
    ("stroke.focus", "2px"),
    ("stroke.hairline", "1px"),
    ("theme.dark.border-default", "#3A3E42"),
    ("theme.dark.border-strong", "#4C4F52"),
    ("theme.dark.border-subtle", "#272A2C"),
    ("theme.dark.canvas", "#101316"),
    ("theme.dark.ink-primary", "#E6E8EB"),
    ("theme.dark.ink-secondary", "#A1A8B1"),
    ("theme.dark.ink-tertiary", "#7E8792"),
    ("theme.dark.inset", "#14171A"),
    ("theme.dark.overlay", "#24282D"),
    ("theme.dark.raised", "#1D2125"),
    ("theme.dark.shell", "#171A1D"),
    ("theme.light.border-default", "#CDD2D9"),
    ("theme.light.border-dimmer", "#D6DAE0"),
    ("theme.light.border-strong", "#B9C0C9"),
    ("theme.light.border-stronger", "#C3C9D1"),
    ("theme.light.border-subtle", "#E0E3E8"),
    ("theme.light.canvas", "#ECEDEF"),
    ("theme.light.danger", "#B93F36"),
    ("theme.light.danger-bg", "#FFECE8"),
    ("theme.light.danger-ink", "#B93F36"),
    ("theme.light.danger-line", "#F2A89E"),
    ("theme.light.info", "#007489"),
    ("theme.light.info-bg", "#DEF9FF"),
    ("theme.light.info-ink", "#007489"),
    ("theme.light.info-line", "#73CEDE"),
    ("theme.light.ink-disabled", "#9AA1AB"),
    ("theme.light.ink-on-interactive", "#F4F7FD"),
    ("theme.light.ink-primary", "#22252A"),
    ("theme.light.ink-secondary", "#6B717A"),
    ("theme.light.ink-tertiary", "#858C96"),
    ("theme.light.inset", "#F2F4F7"),
    ("theme.light.interactive-blue", "#255DA5"),
    ("theme.light.overlay", "#FDFDFF"),
    ("theme.light.raised", "#FBFCFE"),
    ("theme.light.shell", "#F8F9FB"),
    ("theme.light.success", "#0F7B1A"),
    ("theme.light.success-bg", "#E8F9E7"),
    ("theme.light.success-ink", "#0F7B1A"),
    ("theme.light.success-line", "#9BCD99"),
    ("theme.light.warning", "#945F00"),
    ("theme.light.warning-bg", "#FDF2DD"),
    ("theme.light.warning-ink", "#945F00"),
    ("theme.light.warning-line", "#D9B979"),
    ("type.body", "15px"),
    ("type.body-lg", "17px"),
    ("type.body-sm", "13px"),
    ("type.caption", "11px"),
    ("type.console", "12.5px"),
    ("type.console-sm", "11px"),
    ("type.display", "40px"),
    ("type.h1", "32px"),
    ("type.h2", "24px"),
    ("type.h3", "20px"),
    ("type.h4", "18px"),
];

pub fn get(name: &str) -> Option<&'static str> {
    ALL.iter()
        .find_map(|(candidate, value)| (*candidate == name).then_some(*value))
}
