<script setup lang="ts">
import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Activity,
  AppWindow,
  BrainCircuit,
  BrushCleaning,
  Bug,
  ChartPie,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  CircleQuestionMark,
  CodeXml,
  Copy,
  Database,
  Disc3,
  Download,
  Eye,
  ExternalLink,
  File,
  FileArchive,
  FileAudio,
  FileCode2,
  FileCog,
  FileImage,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileVideo,
  Folder,
  FolderPlus,
  Gamepad2,
  Globe2,
  HardDrive,
  History,
  House,
  Info,
  Languages,
  LayoutGrid,
  List,
  ListTree,
  Mail,
  MapPin,
  MessagesSquare,
  Minus,
  Monitor,
  Package,
  PackageX,
  PanelLeftClose,
  PanelLeftOpen,
  Presentation,
  Power,
  RefreshCw,
  Rocket,
  ScanSearch,
  Search,
  Settings,
  ShieldCheck,
  Square,
  Sparkles,
  SunMoon,
  Trash2,
  Video,
  Wallpaper,
  X,
} from '@lucide/vue';
import {
  IconApps,
  IconAutomation,
  IconBinary,
  IconBrain,
  IconBrandAdobe,
  IconBrandAndroid,
  IconBrandApple,
  IconBrandArc,
  IconBrandChrome,
  IconBrandCSharp,
  IconBrandDingtalk,
  IconBrandDeno,
  IconBrandDocker,
  IconBrandDiscord,
  IconBrandEdge,
  IconBrandFigma,
  IconBrandFirefox,
  IconBrandFlutter,
  IconBrandGolang,
  IconBrandGoogle,
  IconBrandGithubCopilot,
  IconBrandNodejs,
  IconBrandNpm,
  IconBrandOffice,
  IconBrandOpenai,
  IconBrandOpera,
  IconBrandPnpm,
  IconBrandPython,
  IconBrandQq,
  IconBrandReactNative,
  IconBrandRust,
  IconBrandSlack,
  IconBrandSwift,
  IconBrandTeams,
  IconBrandTelegram,
  IconBrandTerraform,
  IconBrandUnity,
  IconBrandVivaldi,
  IconBrandVisualStudio,
  IconBrandVscode,
  IconBrandWechat,
  IconBrandWhatsapp,
  IconBrandWindows,
  IconBrandYarn,
  IconBrandZoom,
  IconBrowser,
  IconClockCog,
  IconCpu2,
  IconCubeSpark,
  IconDatabaseCog,
  IconFileTime,
  IconFolders,
  IconLogs,
  IconPackages,
  IconTerminal2,
} from '@tabler/icons-vue';
import {
  siCmake,
  siGodotengine,
  siGradle,
  siHomebrew,
  siHuggingface,
  siJetbrains,
  siOllama,
  siXcode,
  type SimpleIcon,
} from 'simple-icons';
import { computed, type Component } from 'vue';

import MdIconAiModel from '@/components/icons/md-icon-ai-model.vue';
import MdIconGithub from '@/components/icons/md-icon-github.vue';
import MdIconLark from '@/components/icons/md-icon-lark.vue';
import MdIconSimpleBrand from '@/components/icons/md-icon-simple-brand.vue';
import { ICON_NAMES } from '@/lib/models/ui';
import { LoggerService } from '@/lib/services/logger-service';

type IconName = (typeof ICON_NAMES)[keyof typeof ICON_NAMES];
type IconFamily = 'custom' | 'lucide' | 'simpleBrand' | 'tabler';
interface IconDefinition {
  component: Component;
  family: IconFamily;
  path?: string;
}

const props = withDefaults(defineProps<{ name: IconName; size?: number; strokeWidth?: number }>(), {
  size: 20,
  strokeWidth: 1.9,
});

const lucide = (component: Component): IconDefinition => ({ component, family: 'lucide' });
const tabler = (component: Component): IconDefinition => ({ component, family: 'tabler' });
const custom = (component: Component): IconDefinition => ({ component, family: 'custom' });
const simpleBrand = (icon: SimpleIcon): IconDefinition => ({
  component: MdIconSimpleBrand,
  family: 'simpleBrand',
  path: icon.path,
});

const iconMap: Record<IconName, IconDefinition> = {
  sparkles: lucide(Sparkles),
  rocket: lucide(Rocket),
  chat: lucide(MessagesSquare),
  processes: lucide(Activity),
  tree: lucide(ListTree),
  brushCleaning: lucide(BrushCleaning),
  chartPie: lucide(ChartPie),
  fileSearch: lucide(FileSearch),
  copy: lucide(Copy),
  history: lucide(History),
  settings: lucide(Settings),
  hardDrive: lucide(HardDrive),
  chevronDown: lucide(ChevronDown),
  chevronUp: lucide(ChevronUp),
  chevronLeft: lucide(ChevronLeft),
  chevronRight: lucide(ChevronRight),
  panelLeftClose: lucide(PanelLeftClose),
  panelLeftOpen: lucide(PanelLeftOpen),
  refresh: lucide(RefreshCw),
  home: lucide(House),
  search: lucide(Search),
  grid: lucide(LayoutGrid),
  list: lucide(List),
  folder: lucide(Folder),
  folderPlus: lucide(FolderPlus),
  file: lucide(File),
  fileText: lucide(FileText),
  fileSpreadsheet: lucide(FileSpreadsheet),
  filePresentation: lucide(Presentation),
  fileArchive: lucide(FileArchive),
  fileAudio: lucide(FileAudio),
  fileVideo: lucide(FileVideo),
  fileImage: lucide(FileImage),
  fileCode: lucide(FileCode2),
  fileSettings: lucide(FileCog),
  aiModel: custom(MdIconAiModel),
  package: lucide(Package),
  disc: lucide(Disc3),
  check: lucide(Check),
  minus: lucide(Minus),
  shield: lucide(ShieldCheck),
  info: lucide(Info),
  github: lucide(MdIconGithub),
  help: lucide(CircleQuestionMark),
  external: lucide(ExternalLink),
  languages: lucide(Languages),
  theme: lucide(SunMoon),
  close: lucide(X),
  database: lucide(Database),
  code: lucide(CodeXml),
  brainCircuit: lucide(BrainCircuit),
  application: lucide(AppWindow),
  cleanupSystemCache: tabler(IconDatabaseCog),
  cleanupUserCache: tabler(IconFolders),
  cleanupApplicationCache: tabler(IconApps),
  cleanupBrowserData: tabler(IconBrowser),
  cleanupApplicationOptimization: tabler(IconCpu2),
  cleanupAiModelCache: tabler(IconBrain),
  cleanupDeveloperTools: tabler(IconTerminal2),
  cleanupProjectArtifacts: tabler(IconPackages),
  cleanupContainerCache: tabler(IconBrandDocker),
  cleanupTemporaryFiles: tabler(IconFileTime),
  cleanupStaleCache: tabler(IconClockCog),
  cleanupDiagnosticLogs: tabler(IconLogs),
  cleanupUniversalBinary: tabler(IconBinary),
  cleanupAutomationCache: tabler(IconAutomation),
  cleanupCrashReports: lucide(Bug),
  cleanupLocationCache: lucide(MapPin),
  cleanupPreviewCache: lucide(Eye),
  modelRepository: tabler(IconCubeSpark),
  brandAdobe: tabler(IconBrandAdobe),
  brandAndroid: tabler(IconBrandAndroid),
  brandApple: tabler(IconBrandApple),
  brandArc: tabler(IconBrandArc),
  brandCSharp: tabler(IconBrandCSharp),
  brandChrome: tabler(IconBrandChrome),
  brandCmake: simpleBrand(siCmake),
  brandDingtalk: tabler(IconBrandDingtalk),
  brandDeno: tabler(IconBrandDeno),
  brandDiscord: tabler(IconBrandDiscord),
  brandEdge: tabler(IconBrandEdge),
  brandFigma: tabler(IconBrandFigma),
  brandFirefox: tabler(IconBrandFirefox),
  brandFlutter: tabler(IconBrandFlutter),
  brandGo: tabler(IconBrandGolang),
  brandGoogle: tabler(IconBrandGoogle),
  brandGithubCopilot: tabler(IconBrandGithubCopilot),
  brandGodot: simpleBrand(siGodotengine),
  brandGradle: simpleBrand(siGradle),
  brandHomebrew: simpleBrand(siHomebrew),
  brandHuggingface: simpleBrand(siHuggingface),
  brandJetbrains: simpleBrand(siJetbrains),
  brandLark: lucide(MdIconLark),
  brandNodejs: tabler(IconBrandNodejs),
  brandNpm: tabler(IconBrandNpm),
  brandOffice: tabler(IconBrandOffice),
  brandOpenai: tabler(IconBrandOpenai),
  brandOpera: tabler(IconBrandOpera),
  brandOllama: simpleBrand(siOllama),
  brandPnpm: tabler(IconBrandPnpm),
  brandPython: tabler(IconBrandPython),
  brandQq: tabler(IconBrandQq),
  brandReactNative: tabler(IconBrandReactNative),
  brandRust: tabler(IconBrandRust),
  brandSlack: tabler(IconBrandSlack),
  brandSwift: tabler(IconBrandSwift),
  brandTeams: tabler(IconBrandTeams),
  brandTelegram: tabler(IconBrandTelegram),
  brandTerraform: tabler(IconBrandTerraform),
  brandUnity: tabler(IconBrandUnity),
  brandVivaldi: tabler(IconBrandVivaldi),
  brandVisualStudio: tabler(IconBrandVisualStudio),
  brandVscode: tabler(IconBrandVscode),
  brandWechat: tabler(IconBrandWechat),
  brandWhatsapp: tabler(IconBrandWhatsapp),
  brandWindows: tabler(IconBrandWindows),
  brandXcode: simpleBrand(siXcode),
  brandYarn: tabler(IconBrandYarn),
  brandZoom: tabler(IconBrandZoom),
  windowsApplication: lucide(Monitor),
  uninstall: lucide(PackageX),
  globe: lucide(Globe2),
  download: lucide(Download),
  game: lucide(Gamepad2),
  mail: lucide(Mail),
  scan: lucide(ScanSearch),
  startup: lucide(Power),
  trash: lucide(Trash2),
  video: lucide(Video),
  wallpaper: lucide(Wallpaper),
  arrowUpDown: lucide(ArrowUpDown),
  arrowUp: lucide(ArrowUp),
  arrowDown: lucide(ArrowDown),
  windowMaximize: lucide(Square),
  windowRestore: lucide(Copy),
};

const icon = computed(() => {
  const definition = (iconMap as Partial<Record<string, IconDefinition>>)[props.name];
  if (definition) return definition;

  // A missing icon must degrade to a visible diagnostic glyph instead of aborting the whole
  // Vue render tree. The stable warning identifies the component contract without user data.
  LoggerService.warn('ui-icon', 'unsupported_icon_name', {
    iconName: typeof props.name === 'string' && props.name ? props.name : 'missing',
  });
  return iconMap.info;
});

// Public icon families expose different render properties. Normalizing them here keeps
// every caller independent from the selected library and keeps brand path data bundled offline.
const rendererProps = computed(() => {
  if (icon.value.family === 'simpleBrand') {
    return { path: icon.value.path };
  }
  if (icon.value.family === 'tabler') return { stroke: props.strokeWidth };
  if (icon.value.family === 'lucide') return { strokeWidth: props.strokeWidth };
  return {};
});
</script>

<template>
  <component :is="icon.component" :size="size" v-bind="rendererProps" aria-hidden="true" />
</template>
